[package]
name = "pallet-xcm-benchmarks"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
version = "0.9.8"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
xcm-executor = { path = "../xcm-executor", default-features = false, features = ["runtime-benchmarks"] }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
xcm = { path = "..", default-features = false, features = ["runtime-benchmarks"] }
log = "0.4.0"

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
pallet-assets = { git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
sp-core = { git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
sp-io = { git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
sp-tracing = { git = "https://github.com/paritytech/substrate" , branch = "dp-jsonrpsee-integration-2" }
xcm-builder = { path = "../xcm-builder" }
xcm = { path = ".." }
# temp
pallet-xcm = { path = "../pallet-xcm" }
polkadot-runtime-common = { path = "../../runtime/common" }
# westend-runtime = { path = "../../runtime/westend", features = ["runtime-benchmarks"] }
polkadot-primitives = { path = "../../primitives" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std"
]
