[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
chain_spec_command = "../polkadot/target/release/polkadot build-spec --chain rococo-local --disable-default-bootnode"
default_command = "../polkadot/target/release/polkadot"

  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob", "-lparachain=debug,runtime=debug"]
  
  [[relaychain.nodes]]
  name = "charlie"
  extra_args = [ "--charlie", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  extra_args = [ "--dave", "-lparachain=debug"]

  [[relaychain.nodes]]
  name = "ferdie"
  extra_args = [ "--ferdie", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "eve"
  extra_args = [ "--eve", "-lparachain=debug"]

# TODO: Add bulk parachain registration option. Register 20 parachains with a specified collator, or even groups
# of parachains each with different collator settings. We will want to change `adder-collator` to control PoV size 
# and PVF preparation time, by scaling it to output a larger merkle tree and mutate it across many transactions - 
# bigger PoV size as well as larger code size.
[[parachains]]
id = 2000
addToGenesis = true
genesis_state_generator = "../polkadot/target/release/undying-collator export-genesis-state --parachain-id=2000 --pov-size=20000 --pvf-complexity=2"

  [parachains.collator]
  name = "collator01"
  command = "../polkadot/target/release/undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000", "--pvf-complexity=2", "--parachain-id=2000"]

[[parachains]]
id = 2001
addToGenesis = true
genesis_state_generator = "../polkadot/target/release/undying-collator export-genesis-state --parachain-id=2001 --pov-size=20000 --pvf-complexity=2"

  [parachains.collator]
  name = "collator02"
  command = "../polkadot/target/release/undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000", "--parachain-id=2001", "--pvf-complexity=2"]

[[parachains]]
id = 2002
addToGenesis = true
genesis_state_generator = "../polkadot/target/release/undying-collator export-genesis-state --parachain-id=2002 --pov-size=20000 --pvf-complexity=2"

  [parachains.collator]
  name = "collator03"
  command = "../polkadot/target/release/undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000", "--parachain-id=2002", "--pvf-complexity=2"]

[[parachains]]
id = 2003
addToGenesis = true
genesis_state_generator = "../polkadot/target/release/undying-collator export-genesis-state --parachain-id=2003 --pov-size=20000 --pvf-complexity=2"

  [parachains.collator]
  name = "collator04"
  command = "../polkadot/target/release/undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000", "--parachain-id=2003", "--pvf-complexity=2"]

[[parachains]]
id = 2004
addToGenesis = true
genesis_state_generator = "../polkadot/target/release/undying-collator export-genesis-state --parachain-id=2004 --pov-size=20000 --pvf-complexity=2"

  [parachains.collator]
  name = "collator05"
  command = "../polkadot/target/release/undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000", "--parachain-id=2004", "--pvf-complexity=2"]

[[parachains]]
id = 2005
addToGenesis = true
genesis_state_generator = "../polkadot/target/release/undying-collator export-genesis-state --parachain-id=2004 --pov-size=20000 --pvf-complexity=2"

  [parachains.collator]
  name = "collator06"
  command = "../polkadot/target/release/undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000", "--parachain-id=2005", "--pvf-complexity=2"]

# TODO: This should not be in here, maybe have a separate file that is included by default ?
[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"